spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/blog?characterEncoding=UTF-8&useSSL=false
    hikari:
      max-lifetime: 3600000

  freemarker:
    cache: false
    suffix: .ftl
    contentType: text/html;charset=UTF-8
    requestContextAttribute: request

  mail:
    host: smtp.mxhichina.com
    username: lhr@lhrsite.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
    port: 25
    password:

  # sql语句  jpa
  jpa:
    show-sql: false


blog:
  upload:
    image:
    # 配置上传图片路径
      path: /var/blog/image/
#      path: /Users/lhr/Desktop
  domain: https://www.lhrsite.com/

server:
# 服务器监听端口
  port: 8089

logging:
  # 日志文件名称
  file: /var/blog/logs/blog.log
  # 日志文件路径
  path: /var/blog/logs

github:
# github授权信息
  clientId: 2e20720cb5be05666 3cf
  clientSecret: 7e9d0205f259d3f516e14a8ac8c107ada6593363



