spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: root
    password: LiuHaoRan114
    url: jdbc:mysql://39.106.23.44:3306/blog?characterEncoding=UTF-8&useSSL=true

  freemarker:
    cache: true
    suffix: .ftl
    contentType: text/html;charset=UTF-8
    requestContextAttribute: request

  mail:
    host: smtp.mxhichina.com
    username: lhr@lhrsite.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
    port: 25
    password:

  # sql语句  jpa
  jpa:
    show-sql: true


blog:
  upload:
    image:
    # 配置上传图片路径
      path: /var/blog/image/
  domain: https://www.lhrsite.com/

server:
# 服务器监听端口
  port: 8080
logging:
  # 日志文件名称
  file: blog.log
  # 日志文件路径
  path: /var/blog/log

github:
# github授权信息
  clientId: 2e20720cb5be056663cf
  clientSecret: 7e9d0205f259d3f516e14a8ac8c107ada6593363



